# Generated by Django 5.0.6 on 2024-06-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('sumario', models.CharField(max_length=500)),
                ('fecha_publicacion', models.DateField()),
                ('observaciones', models.CharField(max_length=500)),
                ('origen', models.CharField(choices=[('ptn', 'PTN'), ('sptn', 'SPTN')], default='ptn', max_length=4)),
                ('texto_de_resolucion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resoluciones',
                'verbose_name_plural': 'Resoluciones',
                'db_table': 'resoluciones',
            },
        ),
        migrations.CreateModel(
            name='ResolucionRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(choices=[('modifica_a', 'MODIFICA_A'), ('amplia_a', 'AMPLIA_A'), ('suspende_a', 'SUSPENDE_A'), ('deroga_a', 'DEROGA_A')], max_length=10)),
                ('res_dest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='res_dest', to='resoluciones.resoluciones')),
                ('res_orig', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='res_orig', to='resoluciones.resoluciones')),
            ],
            options={
                'verbose_name': 'Resolucion_Relacion',
                'verbose_name_plural': 'Resolucion_Relaciones',
                'db_table': 'resolucion_relacion',
            },
        ),
    ]
